Промени по switch бутони
kiwitcms/Kiwi pull request #2028
Opened 2020-10-22 08:12 UTC by Allexander203

Промени по<input class="bootstrap-switch"> бутони, добавил съм data-on-text="{% trans 'Yes' %}" data-off-text="{% trans 'No' %}" към тагът, както ми е зададено в BACKLOG документът.

2020-10-22 08:33 UTC, RMadjev requested changes
First of all use English only. Also do these changes in single commit and describe better what you did in the commit. I good practice for the commit message is to use this: "If applied, this commit will _your subject line here_". ref. to this article https://chris.beams.io/posts/git-commit/

2020-10-22 08:33 UTC, atodorov requested changes
Change Title & description to English!

2020-10-23 08:06 UTC, RMadjev requested changes
Again you used 4 commits. We want just one with informative descriptive message.

2020-10-23 09:34 UTC, atodorov requested changes
HTML changes look good but you have failing tests which need to be fixed:
https://github.com/kiwitcms/Kiwi/pull/2028/checks?check_run_id=1297210061

2020-11-05 16:16 UTC, atodorov requested changes

2020-11-05 16:16 UTC, atodorov commented on tcms/testplans/tests/test_new_plan.py
> +
flake8 complains about this: `W293 blank line contains whitespace`

2020-11-06 11:58 UTC, atodorov submitted a review, later dismissed

2020-11-06 12:43 UTC, merged