Reformat the file and remove semicolons
kiwitcms/Kiwi pull request #2094
Opened 2020-11-16 18:07 UTC by asankov

to be consistent with the other parts of the file and of the new JS ones

2020-11-16 19:57 UTC, atodorov requested changes

2020-11-16 19:57 UTC, atodorov commented on tcms/testruns/static/testruns/js/get.js
> +        for (var i = 0 i < executionStatuses.length i++) {
SyntaxError: missing ; after for-loop initializer

2020-11-17 08:55 UTC, asankov commented on tcms/testruns/static/testruns/js/get.js
> +        for (var i = 0 i < executionStatuses.length i++) {
```suggestion
        for (var i = 0; i < executionStatuses.length; i++) {
```

2020-11-17 09:31 UTC, atodorov requested changes

2020-11-17 09:31 UTC, atodorov commented on tcms/testruns/static/testruns/js/get.js
> +            const targetUrl = result.response.replace(/&amp/g, '&')
bring back the `;`

2020-11-17 10:11 UTC, asankov commented on tcms/testruns/static/testruns/js/get.js
> +            const targetUrl = result.response.replace(/&amp/g, '&')
```suggestion
            const targetUrl = result.response.replace(/&amp;/g, '&')
```

2020-11-17 12:57 UTC, merged