Add testruns card in testplan page
kiwitcms/Kiwi pull request #2136
Opened 2020-12-05 22:13 UTC by RMadjev

2020-12-05 22:14 UTC, RMadjev commented
![Screenshot_20201206_001124](https://user-images.githubusercontent.com/8727922/101266500-f2325780-3757-11eb-8a18-375fb3d66e2a.png)
![Screenshot_20201206_001102](https://user-images.githubusercontent.com/8727922/101266501-f3638480-3757-11eb-9284-6aaf0a0d68d1.png)

2020-12-05 22:15 UTC, RMadjev commented
TestRun card location, at the bottom or to fill the blank space next to the attachments card?

2020-12-05 22:55 UTC, atodorov commented
> TestRun card location, at the bottom or to fill the blank space next to the attachments card?

Don't change the size of Tags and Attachments cards and add the new one next to them.

2020-12-08 22:56 UTC, RMadjev commented
![testrun](https://user-images.githubusercontent.com/8727922/101551193-52740400-39b9-11eb-87f2-c7d72e636ef7.png)

2020-12-08 22:58 UTC, RMadjev commented
Do we need some extra info in the new card? Also, should we show all of the TR or the last 5?

2020-12-09 12:56 UTC, atodorov requested changes

2020-12-09 12:56 UTC, atodorov commented on tcms/testplans/templates/testplans/get.html
> +                    <h2 class="card-pf-title">
Use fa-forward for icon.

2020-12-09 12:56 UTC, atodorov commented on tcms/testplans/templates/testplans/get.html
> +                        {% trans 'Test Runs' %}
Active test runs

2020-12-09 12:56 UTC, atodorov commented on tcms/testplans/templates/testplans/get.html
> +    <template id="test_run_row">
indentation

2020-12-09 12:56 UTC, atodorov commented on tcms/testplans/static/testplans/js/get.js
> +    jsonRPC('TestRun.filter', {plan: testPlanId}, function(data) {
We need only active TRs shown, last 5 only, most recent first. 

Given these constraints it may be easier to render on the backend directly.

2020-12-09 12:56 UTC, atodorov commented on tcms/testplans/static/testplans/js/get.js
> +    row.find('.js-test-run-summary').html(`TR-${testRun.id}: ${testRun.summary}`).attr('href', '/runs/search');
URL is wrong, should point to the URL for this particular TR.

2020-12-09 12:59 UTC, atodorov commented
> Do we need some extra info in the new card? 

Needs links like `More | Inactive` or `Running: Yes | No` which will load the search page with appropriate URL parameters so that all TRs can be displayed.

> Also, should we show all of the TR or the last 5?

We show only the last 5 or so (we can change this value later) b/c there could be many more available.

2020-12-10 23:27 UTC, RMadjev commented
![Uploading testruns.png…]()

2020-12-10 23:28 UTC, RMadjev commented
![testruns](https://user-images.githubusercontent.com/8727922/101842155-1aeb9000-3b50-11eb-8605-e2768e636c00.png)

2020-12-11 21:52 UTC, atodorov requested changes
Rearrange the cards in this order: 
Active test runs | Tags | Attachments

2020-12-11 21:52 UTC, atodorov commented on tcms/testplans/templates/testplans/get.html
> +                        {% trans 'Active Test Runs' %}
`Active test runs` - capitalization !

2020-12-11 21:52 UTC, atodorov commented on tcms/testplans/views.py
> +            stop_date__isnull=False).filter(plan_id=self.object.pk).order_by('start_date')[:5]
this can be filter(stop_date__isnull=True) instead of a negative condition.

2020-12-11 21:52 UTC, atodorov commented on tcms/testplans/views.py
> +            stop_date__isnull=False).filter(plan_id=self.object.pk).order_by('start_date')[:5]
Shows the oldest 5 records, not the most recent 5.

2020-12-11 21:52 UTC, atodorov commented on tcms/testplans/templates/testplans/get.html
> +                                                        {{ test_run }}
Use `TR-xy: <summary>`

2020-12-11 21:52 UTC, atodorov commented on tcms/testplans/templates/testplans/get.html
> +                            </div>
Missing the corresponding URL/button for searching inactive test runs.

2020-12-15 10:02 UTC, atodorov requested changes

2020-12-15 10:02 UTC, atodorov commented on tcms/testruns/views.py
> +        if self.request.GET.get('running') is not None and self.request.GET.get('running') == "0":
.get('running', None) == "0"

2020-12-15 10:02 UTC, atodorov commented on tcms/testruns/views.py
> +            'running': show_running
Must become a form field

2020-12-20 11:58 UTC, atodorov requested changes
reformat with black

2020-12-20 11:58 UTC, atodorov commented on tcms/testruns/templates/testruns/search.html
> +                <input class="bootstrap-switch" id="id_running" name="running" type="checkbox" {% if form.running.value != "0" %} checked="checked"{% endif %}>
FYI https://stackoverflow.com/a/24588369/1431647

2020-12-21 21:28 UTC, atodorov approved these changes

2020-12-21 21:28 UTC, merged