Added new line
kiwitcms/Kiwi pull request #2209
Opened 2021-01-20 17:28 UTC by Allexander203

2021-01-21 08:22 UTC, atodorov requested changes
Multiple changes requested. Also:

- squash all commits together so that there is only 1 left at the end
- update commit log message to be more meaningful
- update PR title to something more meaningful

2021-01-21 08:22 UTC, atodorov commented on kiwi_lint/forms.py
> +    name = 'form-field-label-checker'
These changes are unrelated. Need to revert them and rebase to latest master !

2021-01-21 08:22 UTC, atodorov commented on tcms/testcases/models.py
> +#pylint:disable=Protected-access
This is a comment inside a documentation string for the function `remove_cc`. It doesn't do anything. Remove it.

2021-01-21 08:22 UTC, atodorov commented on tcms/testcases/models.py
> +            return [] #pylint:disable=Protected-access
Dos this have anything to do with silencing the `form-field-help-text-used` ? It is not even in the right location.

2021-01-21 08:22 UTC, atodorov commented on tcms/testcases/models.py
> +                emailaddr_list.remove(address)#pylint:disable=Protected-access
Dos this have anything to do with silencing the `form-field-help-text-used` ? It is not even in the right location.

2021-01-21 12:00 UTC, atodorov requested changes

2021-01-21 12:00 UTC, atodorov commented on tcms/testcases/models.py
> -
Unrelated change, restore it like it was before.

2021-01-21 12:00 UTC, atodorov commented on tcms/testcases/models.py
> +    api_url = models.CharField(# pylint:disable=form-field-help-text-used
All of the comments trigger flake8 errors. Check the logs or see Makefile how to execute flake8 locally.

2021-01-21 15:45 UTC, asankov requested changes

2021-01-21 15:45 UTC, asankov commented on tcms/testcases/models.py
> +                emailaddr_list.remove(address)  # pylint:disable=Protected-access
this is not needed. there is no alert to silence on this line. revert it.

2021-01-21 15:45 UTC, asankov commented on tcms/testcases/models.py
> +            return []  # pylint:disable=Protected-access
this is not needed. there is no alert to silence on this line. revert it.

2021-01-21 15:45 UTC, asankov commented on kiwi_lint/forms.py
> +
revert this

2021-01-21 16:26 UTC, asankov submitted a review, later dismissed

2021-01-21 16:48 UTC, atodorov requested changes
Changes look good however the commit log still doesn't tell us much about why or what are you doing. See from previous review item:

- update commit log message to be more meaningful

"Successfully disabled pylint" doesn't mean anything for anyone else but you.

2021-01-22 09:39 UTC, atodorov approved these changes

2021-01-22 09:39 UTC, merged