Changed include tag
kiwitcms/Kiwi pull request #2217
Opened 2021-01-22 13:14 UTC by Allexander203

2021-01-22 14:03 UTC, atodorov requested changes

2021-01-22 14:03 UTC, atodorov commented on tcms/bugs/templates/bugs/search.html
> +            {% include "include\datetimepicker_script.html" with selector="#id_after" %}
Use forward slash characters -> `/`

2021-01-22 14:03 UTC, atodorov commented on tcms/testcases/models.py
> +    tracker_type = models.CharField(  # pylint:disable=form-field-help-text-used
Rebase to remove old commits

2021-01-22 14:03 UTC, atodorov commented on tcms/templates/datetimepicker_script.html
> -<script>
File is deleted but the new file in `tcms/templates/include/datetimepicker_script.html` is not added to this pull request.

2021-01-22 16:20 UTC, atodorov requested changes
Previously requested changes still not implemented.

2021-01-22 19:35 UTC, atodorov requested changes
Squash all commits together.

2021-01-28 11:29 UTC, atodorov submitted a review, later dismissed
@asankov diff looks good to me. Feel free to merge when you are happy with how the commit log looks like.

2021-01-28 12:49 UTC, asankov approved these changes

2021-01-28 12:49 UTC, merged