Erased navigation and everything related to it
kiwitcms/Kiwi pull request #2239
Opened 2021-02-05 13:16 UTC by Allexander203

2021-02-05 13:44 UTC, asankov requested changes

2021-02-05 13:44 UTC, asankov commented on tcms/urls.py
>      ),
you also need to delete the call to `re_path`

2021-02-05 13:54 UTC, asankov requested changes

2021-02-05 13:54 UTC, asankov commented on tcms/urls.py
> +
delete the empty line

2021-02-05 13:54 UTC, asankov commented on tcms/core/tests/test_views.py
>  class TestDashboard(BaseCaseRun):
you should have only 2 empty rows between class definitions

2021-02-05 17:47 UTC, atodorov requested changes

2021-02-05 17:47 UTC, atodorov commented on tcms/core/tests/test_views.py
> -    TestPlanFactory,
Some of these imports are still in use, see the failing checks at https://github.com/kiwitcms/Kiwi/pull/2239/checks?check_run_id=1839431769 and https://github.com/kiwitcms/Kiwi/pull/2239/checks?check_run_id=1839432801 for example.

2021-02-10 09:35 UTC, atodorov commented
Cleaned up in https://github.com/kiwitcms/Kiwi/pull/2247

2021-02-10 09:35 UTC, closed without merging