Fixes #2263, #2264: Removes links and icons from print
kiwitcms/Kiwi pull request #2268
Opened 2021-02-26 15:44 UTC by pandafy

Closes #2263 
Closes #2264 

@atodorov this is a draft implementation, what do you think about it? Would be good to generalise it such that it applies to `get` views of other models(Test Plan, Test Case) as well? 

Also, will you be able to share some hints on how to write tests for this?

2021-02-26 15:59 UTC, pandafy commented
@dkoerner85 does this look good to you? 

![image](https://user-images.githubusercontent.com/32094433/109323517-8ef92280-7879-11eb-83fe-115168c1e0ea.png)

2021-02-26 20:52 UTC, atodorov requested changes

2021-02-26 20:52 UTC, atodorov commented on tcms/static/style/patternfly_override.css
> +    }
Patternfly already has the `.hidden-print` class definition and we'd like to use that as much as possible.

Also we want to have elements in  HTML templates explicitly marked with this class to that it is clear they are not intended to be printed on the screen. 

An extension for the `:after` elements showing the URLs will be needed probably.

2021-02-27 11:38 UTC, dkoerner85 commented
> @dkoerner85 does this look good to you?
> ![image](https://user-images.githubusercontent.com/32094433/109324171-4f7f0600-787a-11eb-847a-07c7572c75dc.png)

That looks pretty clean to me!

2021-03-02 08:02 UTC, atodorov requested changes
Minor changes requested. 

info icon for bugs & hyperlinks doesn't need to be printed as well.

2021-03-02 08:02 UTC, atodorov commented on tcms/testruns/templates/testruns/get.html
> +                                        <div class="col-md-6 hidden-print">
This hides all existing comments and attachments as well, not only the form.

2021-03-02 08:05 UTC, atodorov requested changes
Status progressbar colors are not printed, only the numbers representing percentages are shown. When you have pass/fail combination this isn't very intuitive b/c everything is the same color. IMO don't print the progressbar at all, leave only the table with statuses.

2021-03-04 09:21 UTC, atodorov commented
> info icon for bugs & hyperlinks doesn't need to be printed as well.

Still unresolved.

2021-03-04 09:31 UTC, pandafy commented
@atodorov can you please point which icons you are referring to? It will be very helpful.

2021-03-04 11:37 UTC, atodorov commented
![bugs_and_hyperlink_icon](https://user-images.githubusercontent.com/1002300/109958273-b83d0700-7cee-11eb-8484-3193b2f14a11.png)

2021-03-04 11:46 UTC, pandafy commented
Oops! I hid the wrong element before. Thanks Alexander! :raised_hands:

2021-03-06 09:32 UTC, merged