test: Test ReadOnlyHistoryAdmin
kiwitcms/Kiwi pull request #2312
Opened 2021-03-23 13:26 UTC by devkapilbansal

Fixes #1604

2021-03-23 16:00 UTC, atodorov requested changes

2021-03-23 16:00 UTC, atodorov commented on tcms/testplans/tests/test_admin.py
> +                reverse("test_plan_url", args=[self.test_plan.pk, old_test_plan_name]),
The second argument is not the name verbatim but a slug. The URL regex imposes limitation to the available characters that's why the assertion fails.

See also `self.test_plan._get_absolute_url()`

2021-03-23 20:22 UTC, atodorov requested changes

2021-03-23 20:22 UTC, atodorov commented on tcms/testplans/tests/test_admin.py
> +                self.test_plan._get_absolute_url(),
This method is dynamic, it evaluates the URL based on the latest name (e.g. after the save).  Grab the URL before you make any changes and reversals.

2021-03-23 20:22 UTC, atodorov commented on tcms/testplans/tests/test_admin.py
> +                self.test_plan._get_absolute_url(),
`_get_absolute_url()` -> `get_absolute_url()` to make pylint happy.

2021-03-24 22:03 UTC, devkapilbansal commented
When testing in different language, why the response code is 404?
```
======================================================================
FAIL: test_history_display_testplan (tcms.testplans.tests.test_admin.TestTestPlanAdmin) [Test fields are read-only]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/Kiwi/Kiwi/tcms/testplans/tests/test_admin.py", line 72, in test_history_display_testplan
    '<input type="text"',
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/django/test/testcases.py", line 479, in assertNotContains
    response, text, status_code, msg_prefix, html)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/django/test/testcases.py", line 434, in _assert_contains
    " (expected %d)" % (response.status_code, status_code)
AssertionError: 404 != 200 : Couldn't retrieve content: Response code was 404 (expected 200)

======================================================================
FAIL: test_history_display_testplan (tcms.testplans.tests.test_admin.TestTestPlanAdmin) [Test Reverting Redirect to Object]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/Kiwi/Kiwi/tcms/testplans/tests/test_admin.py", line 82, in test_history_display_testplan
    old_test_plan_url,
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/django/test/testcases.py", line 336, in assertRedirects
    % (response.status_code, status_code)
AssertionError: [] is not true : Response didn't redirect as expected: Response code was 404 (expected 302)
```

2021-03-25 07:39 UTC, atodorov commented
> When testing in different language, why the response code is 404?
> 

404 is page not found. As to why you need to debug and figure it out. Print the content returned in the response and also experiment with and without the `follow=True` argument to see what happens.

2021-03-25 10:25 UTC, devkapilbansal commented
@atodorov this PR is ready to review now.

2021-03-25 10:34 UTC, merged