Add init-db docs and auto-activate first user
kiwitcms/Kiwi pull request #2315
Opened 2021-03-24 09:05 UTC by schwarzkrieger

Refs #1698

2021-03-24 09:08 UTC, schwarzkrieger commented
I need to rework tcms.kiwi_auth.tests.test_views to handle the first user auto activation.

2021-03-24 11:37 UTC, atodorov requested changes

2021-03-24 11:37 UTC, atodorov commented on docs/source/installing_docker.rst
> +
The sequence of actions and documentation doesn't make logical sense. Assuming you start with a fresh system you need the minimum amount of documentation in order to get the system up and running. Which already is:

1) web approach: Go to https://localhost (or FQDN) and follow the prompts or 

cli approach:
2) Use the initial_setup cli command which is comprised of migrate + createsuperuser + set_domain + refresh_permissions. <- the command which we want people to use is initial_setup. The rest should be mentioned without too much information. It is expected that if you are going to use them you know what they are. If you don't stick to initial_setup.

Notes:
refresh_permissions is documented in admin.rst
set_domain is documented in the next section

createsuperuser isn't documented from what I can see.

In addition all commands have a 1 line documentation in admin.rst as well so we don't have to repeat that too much.

2021-03-24 11:37 UTC, atodorov commented on tcms/kiwi_auth/forms.py
> +            user.is_active = True
this will needs tests.

2021-03-30 07:24 UTC, atodorov requested changes
Minor changes requested.

Squash all commits afterwards b/c this will be ready to be merged.

2021-03-30 07:24 UTC, atodorov commented on docs/source/installing_docker.rst
> +``https://<your_domain_or_ip>/init-db/``
Add `.. versionadded:: 10.1`, see for syntax above

2021-03-30 07:24 UTC, atodorov commented on docs/source/installing_docker.rst
> +
Remove this block. We don't want to recommend performing web based migrations for upgrades.

2021-03-31 07:03 UTC, merged