Update runs/get with 2 new fields Refs. #1928
kiwitcms/Kiwi pull request #2318
Opened 2021-03-25 12:35 UTC by AirinB

2021-03-25 12:53 UTC, atodorov commented
Blocked by #2307 b/c we can't check if something looks well on the screen if we can't edit/set the values in the first place.

2021-03-28 10:25 UTC, AirinB commented
@atodorov I have used the changes in this [PR](https://github.com/kiwitcms/Kiwi/pull/2307#issuecomment-808876546) and this is how those 2 fields look like. Seems to be displaying the right value, but do you think I should also add some validation? Since the planned stop can be before the planned start right now...
![Screen Shot 2021-03-28 at 12 21 03 PM](https://user-images.githubusercontent.com/27647952/112749107-7ab35d00-8fc0-11eb-96f2-d1c415c98f6b.png)

2021-03-29 08:16 UTC, atodorov requested changes
Minor changes requested, rebase to latest master to see the changes for runs/edit page.

2021-03-29 08:16 UTC, atodorov commented on tcms/testruns/templates/testruns/get.html
> +                </h2>
Interlace these 2 fields with the other calendar fields. Planned start -> Start -> Planned stop -> Finish date

2021-03-29 08:16 UTC, atodorov commented on tcms/testruns/templates/testruns/get.html
> +                    <a href="{% url 'testruns-search' %}?product={{ object.plan.product_id }}" title="Planned stop {{ object.planned_stop }}">{{ object.planned_stop}}</a>
Remove search URL. Moreover as-is it is incorrect anyway b/c it points to the product.

2021-03-29 10:49 UTC, atodorov requested changes
Minor change requested.

This is the last change related to this issue. Modify the commit log with a `Closes` or `Fixes` message so that GitHub will close the related issue automatically.

2021-03-29 10:49 UTC, atodorov commented on tcms/testruns/templates/testruns/get.html
> +                    {{ object.planned_start}}
Use a `|default:'-'` template filter in order to print a dash `-` instead of `None` when these fields don't have a value.

2021-03-29 11:31 UTC, merged