gitlab: use urlparse instead of manually parsing the base_url
kiwitcms/Kiwi pull request #2758
Opened 2022-03-30 15:45 UTC by cmeissl

`repo_id` currently always returns the last two segments of the `base_url`.
For projects under a sub group it removes parts of the group hierachy which results
in a `404` when trying to create a Issue from within `Kiwi`.

fixes #2643

2022-03-30 18:27 UTC, atodorov requested changes
Needs some fixes.

Also needs an additional test for the case where project name has 3 components separated by a slash, see `tests/gitlab_ce/initialize-data` and `tcms/issuetracker/tests/test_gitlab_ee.py`.

2022-03-30 18:27 UTC, atodorov commented on tcms/issuetracker/gitlab_integration.py
> +from urllib.parse import urlparse
see flake8, isort and black checks.

2022-03-30 18:27 UTC, atodorov commented on tcms/issuetracker/gitlab_integration.py
> +        return urlparse(bug_system.base_url).path.lstrip('/')
Looks like this is also causing the existing tests to fail.

2022-03-31 08:33 UTC, cmeissl commented on tcms/issuetracker/gitlab_integration.py
> +        return urlparse(bug_system.base_url).path.lstrip('/')
right, thanks, should be fixed now

2022-03-31 08:45 UTC, cmeissl commented
> Needs some fixes.
> 
> Also needs an additional test for the case where project name has 3 components separated by a slash, see `tests/gitlab_ee/initialize-data` and `tcms/issuetracker/tests/test_gitlab_ee.py`.

Thanks for pointing me into the right direction. I have extended `initialize-data` to create the hierachy for testing projects in groups `group->sub_group->kiwitcms_in_group`. 

The gitlab tests have been extended with:
- `test_bug_id_from_url_in_group`
- `test_details_for_public_url_in_group`

The tests in the CI are now green again for gitlab, but some other unrelated tests seem to fail, at least I fail to see how
this PR could have broken the other tests.

2022-04-25 08:13 UTC, merged